POST http://localhost:8080/auth/register/patient
Content-Type: application/json

{
  "username": "patient1",
  "password": "123456",
  "name": "John Doe",
  "phoneNumber": "0123456789",
  "gender": "Male",
  "address": "123 Street",
  "dateOfBirth": "1990-05-01"
}
### Doctor signup
POST http://localhost:8080/auth/register/doctor
Content-Type: application/json

{
"username": "doctor1"
}


### Doctor login or patient login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "patient1",
  "password": "123456"
}
### Create a new doctor (admin only)
POST http://localhost:8080/api/doctors
Authorization: Bearer <admin_jwt_token>
Content-Type: application/json

{
"username": "doctor2",
"password": "password123",
"name": "Dr. Alice",
"phoneNumber": "0123456789",
"specialization": "Cardiology",
"gender": "Female",
"experienceYears": 5,
"address": "123 Street",
"dateOfBirth": "1985-03-10"
}

### Get all doctors (admin only)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "h@youssef",
  "password": "123456"
}

### Doctor login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "M@Ahmed",
  "password": "123456"
}