### Create medical record for patient
POST http://localhost:8080/api/medical-records
Content-Type: application/json

{
  "patient": { "id": 1 }
}

### Get all records
GET http://localhost:8080/api/medical-records
Accept: application/json

### Get record by ID
GET http://localhost:8080/api/medical-records/1
Accept: application/json

### Get records for patient
GET http://localhost:8080/api/medical-records/patient/1
Accept: application/json
