###create a new appointment
POST http://localhost:8081/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJzdWIiOiJmYXRlbkBnYW1haWwuY29tIiwiaWF0IjoxNzY2MjQzMTg3LCJleHAiOjE3NjYyNDY3ODd9.B20yN6vOpEgUrNnv-jth965CseDds7Vp5mspG6ItEYs

{
  "doctorId": 3,
  "appointmentDate": "2024-07-10T10:00:00Z",
  "reason": "Regular check-up"
}

###get all doctors
GET http://localhost:8081/doctors/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJuYW1lIjoibW9oYW1lZCIsInN1YiI6Im1vQGNvbSIsImlhdCI6MTc2Njc0Mzk2MiwiZXhwIjoxNzY2NzQ3NTYyfQ.a0o1FhcoZ-EMnwCQ7F_b7rxW2BeDF4o0bxEBAJ9_bJI

###get all appointments for patient
GET http://localhost:8081/appointments/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJuYW1lIjoibW9oYW1lZCIsInN1YiI6Im1vQGNvbSIsImlhdCI6MTc2Njc1MDU2NSwiZXhwIjoxNzY2NzU0MTY1fQ.Miwyk9gzhvcwcvRYtX1Gwez-yKJ5sVgxPRINWxVYoJ0

###get apppoinment for doctor by id
GET http://localhost:8081/appointments/doctor/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0RPQ1RPUiIsIm5hbWUiOiJNYWxjb2xtIEJyb3duIiwic3ViIjoiQ2xpbnRfTWFycXVhcmR0ODhAeWFob28uY29tIiwiaWF0IjoxNzY2NzUwNTIxLCJleHAiOjE3NjY3NTQxMjF9.FRJoxUCu7QnYhbD_zwkB8wS_dCnA7wgqBP2JU2oViMQ

###get all appointments for admin
GET http://localhost:8081/appointments/admin/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2Njc0MzM3MCwiZXhwIjoxNzY2NzQ2OTcwfQ.1zNSj-9_xvt9lTIbIcTkST4a8aYVU-RM_Tspl0gT380