###create a new appointment
POST http://localhost:8081/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJzdWIiOiJmYXRlbkBnYW1haWwuY29tIiwiaWF0IjoxNzY2MjQzMTg3LCJleHAiOjE3NjYyNDY3ODd9.B20yN6vOpEgUrNnv-jth965CseDds7Vp5mspG6ItEYs

{
  "doctorId": 3,
  "appointmentDate": "2024-07-10T10:00:00Z",
  "reason": "Regular check-up"
}

###get all doctors
GET http://localhost:8081/doctors/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJzdWIiOiJmYXRlbkBnYW1haWwuY29tIiwiaWF0IjoxNzY2MjQzMTg3LCJleHAiOjE3NjYyNDY3ODd9.B20yN6vOpEgUrNnv-jth965CseDds7Vp5mspG6ItEYs

###get all appointments for patient
GET http://localhost:8081/appointments/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJzdWIiOiJmYXRlbkBnYW1haWwuY29tIiwiaWF0IjoxNzY2MjQzMTg3LCJleHAiOjE3NjYyNDY3ODd9.B20yN6vOpEgUrNnv-jth965CseDds7Vp5mspG6ItEYs

###get apppoinment for doctor by id
GET http://localhost:8081/appointments/doctor/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0RPQ1RPUiIsInN1YiI6IkJlbm5ldHRfS2VybHVrZTQxQGhvdG1haWwuY29tIiwiaWF0IjoxNzY2MjU1MjE4LCJleHAiOjE3NjYyNTg4MTh9.7hGKOBdh--ZMiijhJ8VuO0U4UZ8OJg-J2CS75NusdWc

###get all appointments for admin
GET http://localhost:8081/appointments/admin/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwic3ViIjoiaC55b3Vzc2VmMjMyM0BudS5lZHUuZWciLCJpYXQiOjE3NjYyNTU1MjksImV4cCI6MTc2NjI1OTEyOX0.HZrJWDm-S8OWXrIYYxK08FSuVTwLxUxjw8xcbnhzuHs