### Get all patients
GET http://localhost:8080/api/patients
Accept: application/json

### Create a new patient
POST http://localhost:8080/api/patients
Content-Type: application/json

{
  "name": "Omar Magdy",
  "email": "omar4@example.com",
  "phoneNumber": "0123456789",
  "gender": "Male",
  "dateOfBirth": "1990-05-15",
  "address": "Cairo, Egypt",
  "medicalHistory": "None"
}

### Get patient by ID
GET http://localhost:8080/api/patients/2
Accept: application/json

### Update patient
PUT http://localhost:8080/api/patients/2
Content-Type: application/json

{
  "name": "Omar Magdy Updated",
  "email": "omar.updated@example.com",
  "phoneNumber": "0123456789",
  "gender": "Male",
  "dateOfBirth": "1990-05-15",
  "address": "Cairo, Egypt",
  "medicalHistory": "Allergic to penicillin"
}

### Delete patient
DELETE http://localhost:8080/api/patients/18


