### get all payments for admin
GET http://localhost:8081/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2NjUyMjkzMCwiZXhwIjoxNzY2NTI2NTMwfQ.KsX0qGeJdy7HOfmYE65xjPvaUbaQ34BemSqbuF1c3ys

### get all pending payments for admin
GET http://localhost:8081/payments/pending
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2NjUyMjkzMCwiZXhwIjoxNzY2NTI2NTMwfQ.KsX0qGeJdy7HOfmYE65xjPvaUbaQ34BemSqbuF1c3ys

### get all payments by method CASH for admin
GET http://localhost:8081/payments/method/CASH
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2NjUyMjkzMCwiZXhwIjoxNzY2NTI2NTMwfQ.KsX0qGeJdy7HOfmYE65xjPvaUbaQ34BemSqbuF1c3ys

### Get patient's pending VISA payments
GET http://localhost:8081/payments/my-pending
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJuYW1lIjoiZmF0ZW4gcmFtYWRhbiIsInN1YiI6ImZhdGVuQGdhbWFpbC5jb20iLCJpYXQiOjE3NjY1MjMxNTUsImV4cCI6MTc2NjUyNjc1NX0.C0nLfBmgUDNWrieAsvdz4EiqoJ08pSlkN5xmmgYQPGQ

### Create a payment for an appointment as patient
POST http://localhost:8081/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJuYW1lIjoiZmF0ZW4gcmFtYWRhbiIsInN1YiI6ImZhdGVuQGdhbWFpbC5jb20iLCJpYXQiOjE3NjY1MjMxNTUsImV4cCI6MTc2NjUyNjc1NX0.C0nLfBmgUDNWrieAsvdz4EiqoJ08pSlkN5xmmgYQPGQ

{
  "appointmentId": 1,
  "paymentMethod": "VISA",
  "cardLast4": "1234"
}

### Approve a payment as admin
PUT http://localhost:8081/payments/1/approve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2NjUyMjkzMCwiZXhwIjoxNzY2NTI2NTMwfQ.KsX0qGeJdy7HOfmYE65xjPvaUbaQ34BemSqbuF1c3ys

### Deny a payment as admin
PUT http://localhost:8081/payments/1/deny
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2NjUyMjkzMCwiZXhwIjoxNzY2NTI2NTMwfQ.KsX0qGeJdy7HOfmYE65xjPvaUbaQ34BemSqbuF1c3ys

### Get payment details by id as admin
GET http://localhost:8081/payments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2NjUyMjkzMCwiZXhwIjoxNzY2NTI2NTMwfQ.KsX0qGeJdy7HOfmYE65xjPvaUbaQ34BemSqbuF1c3ys

### Delete payment by id as admin
DELETE http://localhost:8081/payments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0FETUlOIiwibmFtZSI6ImhfeW91c3NlZjIzMjMiLCJzdWIiOiJoLnlvdXNzZWYyMzIzQG51LmVkdS5lZyIsImlhdCI6MTc2NjUyMjkzMCwiZXhwIjoxNzY2NTI2NTMwfQ.KsX0qGeJdy7HOfmYE65xjPvaUbaQ34BemSqbuF1c3ys

### Get payment details by id as doctor
GET http://localhost:8081/payments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX0RPQ1RPUiIsIm5hbWUiOiJNYWxjb2xtIEJyb3duIiwic3ViIjoiQ2xpbnRfTWFycXVhcmR0ODhAeWFob28uY29tIiwiaWF0IjoxNzY2NTI1MzUyLCJleHAiOjE3NjY1Mjg5NTJ9.RhmJEizSAVSP_olhPx62gNSDH_oTgd8UpS1kzQQ8tYo

### Get patient's payments as patient
GET http://localhost:8081/payments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9ST0xFX1BBVElFTlQiLCJuYW1lIjoibW9oYW1lZCIsInN1YiI6Im1vQGNvbSIsImlhdCI6MTc2NjUyNTQ3OCwiZXhwIjoxNzY2NTI5MDc4fQ.2rsR1uBK1R2bfer8q0nwBEc_-6WjFq2q1Zj4MsV9SWI