### signup new user
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "faten",
  "email": "faten.ramadan.mohamed@gmail.com",
  "password": "123456"
}
### login existing user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
"email": "faten.ramadan.mohamed@gmail.com",
"password": "123456"
}
### verify user email
POST http://localhost:8080/auth/verify
Content-Type: application/json

{
"email": "faten.ramadan.mohamed@gmail.com",
"verificationCode": "484875"
}

###signup another user
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "hajar",
  "email": "hajarmuhammad903@gmail.com",
  "password": "123456"
}